### ISSUE TITLE
[MVP QA] MyShelf

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1407]
### Descriptive summary 

user generated collections; batch download of myshelf;

### Expected behavior

- [ ] Create new personal collection: add title and description
  - [x] As an OSU user 
  - [ ] As a UO user 
  - [ ] As an unaffiliated user
  - [x] Confirm required fields are enforced 
  - [x] Confirm messaging that personal collection is being created
  - [x] Confirm that personal collection has been created

- [x] Edit personal collection: retitle, change description
  - [x] Confirm changes

- [x] Deleted personal collection
  - [x] Confirm messaging that personal collection is being deleted
  - [x] Confirm deletion

- [x] Add items to personal collection
  - [x] From search results (list view)
  - [x] From search results (grid view)
  - [x] From an item page 
  - [x] Confirm messaging that item has been added
  - [x] Confirm item has been added
  - [x] Confirm that previously-created collection is searchable in add dialog

- [x] Remove items from personal collection 
  - [x] Confirm messaging that item is being deleted
  - [x] Confirm that item has been deleted

- [x] Download all items and metadata from personal collection
  - [x] Confirm messaging that all items are being downloaded
  - [x] Confirm items and metadata have been downloaded

- [x] Download selected items and metadata from personal collection
  - [x] Confirm messaging that selected items are being downloaded
  - [x] Confirm items and metadata have been downloaded

- [ ] Share personal collection
  - [x] Make a personal collection sharable
  - [x] Confirm that collection is viewable to someone else
    - [ ] To a registered user
    - [x] To an unregistered user
  - [ ] Confirm that restricted items are not viewable to users without permissions

### Related work

#258, #260, #261, #643, #684, #685, #1143, #1144, #1145, #1146, #1150, #1151, #1152, #1153, #1154, #1164, #1169, #1174, #1175, #1179, #1180, #1181, #1182, #1183, #1188, #1193, #1241, #1242, #1243, #1247, #1248, #1317, #1318

**Comment by kmthorn** [comment]
Use only these user roles
- UO affiliated user
- OSU affiliated user
- Non-affiliated user

Use these collections and items for Shelf QA
- UO restricted collection that has no streaming media associated with it: [https://github.com/OregonDigital/OD2/issues/1356](https://github.com/OregonDigital/OD2/issues/1356) 213 items total in this collection are viewable to UO affiliated users. 116 for a non-affiliated user
- UO restricted image simple object [https://staging.oregondigital.org/concern/images/df66z971d?locale=en#metadata](https://staging.oregondigital.org/concern/images/df66z971d?locale=en#metadata)
- UO restricted dataset simple object [https://staging.oregondigital.org/concern/generics/df661w36p?locale=en](https://staging.oregondigital.org/concern/generics/df661w36p?locale=en)
- UO non-restricted interview compound object [https://staging.oregondigital.org/concern/images/df66z971d?locale=en#metadata](https://staging.oregondigital.org/concern/images/df66z971d?locale=en#metadata)
- UO non-restricted manuscript compound object [https://staging.oregondigital.org/concern/generics/df727084j?locale=en](https://staging.oregondigital.org/concern/generics/df727084j?locale=en)

**Comment by kmthorn** [comment]
QA Fail. There are a lot of problems. Kate and Chris will make a video of the issues.

**Comment by petersec** [comment]
Ticket review in process. So far we have been able to create, label and describe multiple collections (one with a single item, one with four items) using OSU credentials. 

However, when seeking to add another item to an existing collection, the type-ahead drop-down does not find our existing collection. This may not be something that is asked of us in this ticket, but is something that will need to be fixed down the line. 

Also, the descriptions that we provided in our test collections disappeared when we sought to edit the collections. There doesn't seem to be any space where the descriptions that we wrote appear at all.

We will continue to work on this ticket in future SM meetings.

**Comment by petersec** [comment]
Mostly completed ticket review - QA fail

Specifics of QA fail:

- From the above, descriptions added to shelf collections disappear once written and saved. We couldn't find any instance of them appearing anywhere once a collection had been created and saved.
- Remove an item - fail because no messaging that the item is being deleted. (There is messaging that the item will be deleted if a user clicks Delete, but we don't interpret that as being the same thing as a message that the item is in the process of being deleted.) Our test item did successfully remove from the collection BUT it's hard to figure out how to do it. Clicking on Edit from the shelf dashboard would seem to be the path, but that doesn't work. Instead, the user has to click on the collection link, then scroll to bottom of the collection landing page, then click remove. 
- Download All -fail.  Toast didn't go away after clicking on Export. Clicking on Export a second time downloaded the content a second time. Toast only goes away after clicking on X-out. No confirmation message that content had downloaded (but can see that it downloaded via Chrome download bar). All items downloaded BUT we expected to receive metadata for the items in the collection. The metadata that we received was at the collection level, and did not describe the items at all.
- Download Selected - fail. There doesn't seem to be any utility within the shelf that allows us to do this. The only way we could figure out how to download a specific item was to click through to the item and download from the item show page.
- Sharing - incomplete. Able to share with an unregistered user. (Kate is having authentication issues with UO that are blocking us from testing with another registered user.) However, the text at bottom of the collection landing page - "Explore More About This Collection" - doesn't have any utility associated with it. (For the creator of the collection, this seems to exist to delete specific items from the collection. Perhaps that's it's only utility?) Also not sure if there are any restricted assets in staging for us to test restricted sharing.
- Retitle a collection - pass
- Delete All - pass

**Comment by CGillen** [comment]
Ready for Service Manager QA.

- Can we make moving the item remove interface an enhancement? Functionality works and isn't in an absolutely absurd place.
- I don't recall selected download functionality. Can that be enhancement too? I'm thinking we can expand the checkbox + save to workflow and just add an export button.

**Comment by petersec** [comment]
@CGillen Yes, I think its fine for both of these to be moved into the enhancement bin.

I will QA the rest of this ticket asap.

**Comment by petersec** [comment]
QA fail (but making progress)

Fail - from the first task, "confirm required fields are enforced." Are there any required fields? I created a collection with no title or metadata and received the 'being created' toast, but it didn't ever show up in My Collections. So presumably there are required fields, but I don't see that they are marked as such and the toast implies to the user that they don't exist.

Fail - all of fourth task, "Add items to personal collection." This seems to be the biggest issue right now. The system was not able to find my test collections from the 'Save This Item' screen. Nothing shows up when I click on the 'Select a collection' dropdown, nor when using the 'Please enter 2 or more characters' search prompt. This is the case from list view, grid view and save from item page.

Pass - Edit Collection tasks
Pass - Delete Collection tasks
Pass - Remove Items tasks
Pass - Download All

@jsimic I'm going to need help with testing as a UO user and an unaffiliated user, sharing with a registered user, and testing with restricted items.

@CGillen I've also struck out the 'Download selected items and metadata' from this ticket, per our decision to make it an enhancement. Create a new ticket for this? Other observations, probably for new/future tickets: breadcrumbs were taking me to the OD2 back end, and the item counts on `https://staging.oregondigital.org/explore_collections/my#content` were stuck on 1.

**Comment by CGillen** [comment]
#2428 fixes the 4th task

**Comment by petersec** [comment]
Everything that I'm able to test is QA Pass.

As an OSU user, I am now able to:

- confirm that required fields are enforced.
- complete all tasks specified under 'Add items to personal collection.'

I did not test anything under 'Download selected items...' since we've decided it's an enhancement.

@jsimic  I will need QA assistance with the UO login tasks, unaffiliated user tasks, sharing with a registered user, and testing with restricted items.

**Comment by jsimic** [comment]
QA Fail. Unable to create a collection as a UO or unaffiliated user. I selected items, saved to a new collection, added the title and description, and got the toast that the collection was being created for both accounts. The collection does not appear under My Collections after 1 hour.

**Comment by straleyb** [comment]
@jsimic @petersec So I ran some tests and noticed that when you create a collection, it does created, but it sets it to private. I checked the collection list from the dashboard (dashboard > collections) and it was there. I swapped it to public and it showed up in the "My Collections" list. Do we want the collections that are created to be automatically set to private or public?

**Comment by jsimic** [comment]
My Collections should be accessible only to the person who created them unless/until they are shared through the My Collections interface. Even if the collection was set to private I should have been able to see it logged into the account that created it, which I was not able to do (and still can't see it on my UO account or my unaffiliated account.)

**Comment by straleyb** [comment]
Perfect. Ill make the update to get the My Collections page to show the private collections of the user that is signed in. 

I also tested out the download functionality and that seemed to work. In the mean time, if you go to the collections and set your collection to public or test the download that should work for MVP reasons.

**Comment by straleyb** [comment]
@jsimic Ok this should be working. I went to search results and created a collection using two items on the search results page. I was able to go to explore collections > my collections as well as the my collections tab in the main drop down. The collection showed up with the items associated with the collection.

**Comment by jsimic** [comment]
@straleyb  Creation collection under my UO account is still not working. Does this need a deploy?

**Comment by kmthorn** [comment]
QA Fail 
- Chris created an unaffiliated user account. He then tried to create 2 test collections. None showed up within 5 minutes. 
- Kate tried logging into the system as a UO affiliated user and was not able to log into the system. She was not able to create new personal collections. @jsimic Are you able to log into staging as a UO user?

**Comment by jsimic** [comment]
@petersec @kmthorn Try this (Slack 10/5): https://osulp.slack.com/archives/C02KRA1TT/p1665006627553949

**Comment by CGillen** [comment]
Note for self: Sharing is broken because of dashboard permissions

**Comment by petersec** [comment]
QA fail for Non-Affiliated User:

- Not able to delete a personal collection. Received the expected messaging, but the collection never went away.
- Not able to add an item to an existing collection. Drop-down did not find the existing collection to which I was seeking to add an item.
- Not able to remove an item from an existing collection. When attempting to do so (after hitting 'Remove' button at bottom of collection show page) was met with error message: "You have tried to access a resource for which you are not authorized."

All of these actions do work for a Non-Affiliated User:
- Create a collection
- Edit collection description
- Download contents of a collection
- Share to Registered User
- Share to Unregistered User

Not sure how to test sharing of a restricted item, because we're not sure which items in Staging (if any) are restricted.

**Comment by kmthorn** [comment]
QA fail for UO authenticated user:

- Not able to delete a personal collection. Received the expected messaging, but the collection never went away.
- Not able to remove an item from an existing collection. When attempting to do so (after hitting 'Remove' button at bottom of collection show page) was met with error message: "You have tried to access a resource for which you are not authorized."
- The first time a UO authenticated user added an item to a new collection, the new collection was created and item added. However, the item was also added to a collection called "my first collection". "My first collection" was not created by the UO authenticated user nor does it appear on the user's My Collections landing page's list of collections. It showed up on the user's "sm-uoauth-20220105" collection at the bottom of the page where the item's "Is part of" is located. See screenshot.
![uoauthuser-savedpersonalcollection](https://user-images.githubusercontent.com/36867009/210870547-fd750445-1106-4161-aa0b-f669fe881a90.jpg)
- Not able to share with a Registered User
- Not able to share with Unregistered User


All of these actions do work for a Non-Affiliated User:
- Create a collection
- Able to add an item to an existing collection.
- Edit collection description
- Download the contents of a collection
- Not sure how to test sharing of a restricted item, because we're not sure which items in Staging (if any) are restricted.

**Comment by CGillen** [comment]
@kmthorn @petersec Maybe I'm not understanding what's wrong here. All of these actions work for me, with an unregistered, registered, and non-admin affiliate account:

- After receiving the message, I refreshed the page and the collection was gone
- This one I may have added a fix at some point, but I can submit a work for delete and get no error page. Maybe there's a set of conditions that causes this error
- This work just happened to be in one of my personal collections. I'm not sure why you can see it, what kind of account were you on? It doesn't appear for a registered user for me
- Share button, copy link, open link. Using the link works for an unregistered, registered, and affiliated accounts.

The very last point I definitely don't understand. I non-admin/curator/etc user shouldn't be able to change the restriction status of a work

**Comment by petersec** [comment]
QA Fail notes -- our testing of Staging today indicates that the below applies to all types of users: UO, OSU and Non-Affiliated.

-  Not able to delete a personal collection. Received the expected messaging, but the collection never went away. (waited 15 minutes)
- Not able to remove an item from an existing collection. When attempting to do so (after hitting 'Remove' button at bottom of collection show page) was met with error message: "You have tried to access a resource for which you are not authorized." Also, upon double-checking the collection, we found that the deleted item was still there.
![Image20230120155446](https://user-images.githubusercontent.com/8129900/213825318-98cbbc74-b51a-4a50-8558-92f028fd056e.jpg)

Since last Service Managers test (January 5), this piece of functionality **is** now working: Add an item to an existing collection. The drop-down menu is now able to find the existing collection as expected, and the item was successfully added.

**An important note about sharing**: Our testing indicates that sharing only works if the user 'enables' the share by clicking the Share link next to the collection's title on the My Collections index page. If the user does not do this, and then attempts to share the collection by copying and passing along the link next to the 'Share This:' prompt on a personal collection's landing page, that link will not open for the user to whom it has been shared. Tl;dr -- you have to enable sharing from the My Collections index page for any sharing of personal collections to work.

RE: test sharing of a restricted item, our notes in the previous comments refer to this component of the ticket: "Confirm that restricted items are not viewable to users without permissions."

**Comment by CGillen** [comment]
Chris/Kate: the text stemming should be the same on regular catalog search now

**Comment by petersec** [comment]
QA Fail notes -- our testing of Staging today indicates that the below applies to OSU and Non-Affiliated users. (Kate was not able to login to Staging using her UO credentials. She is working with Andy at UO USS-Academic Self to remedy this.)

-  Not able to delete a personal collection. Received the expected messaging, but the collection never went away. (waited 15 minutes)
- Not able to remove an item from an existing collection. When attempting to do so (after hitting 'Remove' button at bottom of collection show page) was met with error message: "You have tried to access a resource for which you are not authorized." Also, upon double-checking the collection, we found that the deleted item was still there.
![Image20230120155446](https://user-images.githubusercontent.com/8129900/213825318-98cbbc74-b51a-4a50-8558-92f028fd056e.jpg)

**Comment by petersec** [comment]
QA pass for OSU login and unaffiliated user. @kmthorn will need to test for UO login.

One little bug that I noticed though -- when adding an item to an existing collection the 'Select a Collection' drop down menu succeeds in searching for letters but not numbers. The collection for which I was searching was titled `20230208 - CP 1407 test for OSU login`; the search box found it when I used `CP` but not `20`.

This bug and the particulars of the 'important note about sharing' added to our QA comment of January 20, 2023 should both be written up as their own tickets. But neither, in my view, constitutes QA fail for 1407.
