### ISSUE TITLE
Column spacing issues on work show pages

### ISSUE THREAD

**Issue by carakey** [OregonDigital/OD2#2369]
### Descriptive summary

The metadata section of a work show page display is buggy in Safari at certain browser window sizes / zoom levels. 

Two columns overlap, as in screenshot:
<img width="1024" alt="Screen Shot 2022-06-30 at 1 47 47 PM" src="https://user-images.githubusercontent.com/17655103/176778118-7a824051-b427-4b7f-94ca-35bce90fa7ed.png">

Bottom of column 1 cuts off, with remainder appearing at top of column 2, as in screenshots:

Column 1, bottom: 
<img width="719" alt="Screen Shot 2022-06-30 at 1 57 32 PM" src="https://user-images.githubusercontent.com/17655103/176777190-9f2b52fb-30be-4fc1-9594-d42390f1f3c5.png">

Column 2, top:
<img width="714" alt="Screen Shot 2022-06-30 at 1 57 20 PM" src="https://user-images.githubusercontent.com/17655103/176777697-f0bbe0c8-7bf5-4910-badd-d5cef4227a42.png">

Notes: 
Appearance is ok in Firefox. 
Column overlap issue becomes ok in Safari if I maximize browser window or zoom out. 
Bottom/top split issue becomes ok if I zoom out (but not resize). 

Macbook Pro 16-inch (3456 × 2234)
Screen resolution is default
Safari version 15.3
View is set to "Actual Size"

### Expected behavior

Text is readable using all major browsers, with appropriate column spacing and automatically adjusting wrapping.

### Accessibility Concerns

Major visual readability problems with column overlap in particular.

**Comment by lharka** [comment]
This also happens on the admin view for OD2 in Chrome when browser size changes. The filters menu and works shown overlap, and facet labels move outside their box borders (see screenshot).

Macbook Pro 13-inch
Screen resolution is default
Chrome Version 103.0.5060.53
View is set to "Actual Size"

![Screen Shot 2022-06-30 at 2 29 25 PM](https://user-images.githubusercontent.com/74078731/176782169-6bf24a49-edbd-4567-978f-e1ed76d085d2.png)

**Comment by carakey** [comment]
Testing on Staging: The overlapping columns issue looks great, and that's definitely the bigger problem, so that's good. 

The issue with text getting split horizontally at the bottom of column 1 / top of column 2 is still happening. See the "Publisher" field in the screenshot below, when the window is sized to where it first expands to 2-column:

![image](https://user-images.githubusercontent.com/17655103/191620992-c261a96b-99e2-418d-a068-104cbcfa6249.png)

If I expand the window size until the metadata fields shift, then it splits "Identifier" instead:

![image](https://user-images.githubusercontent.com/17655103/191621334-0511ba93-7511-40fd-84c0-1e92312a0d17.png)

If I continue to expand to full width, then I get tidy fields.  

_Captured from https://staging.oregondigital.org/concern/documents/3t945r17t on 2022-09-21 using Safari and other settings as initially reported._

I can also state that the related(?) Dashboard issue Leslie reported looks ok for me on Prod in Safari but does occur in Firefox. At this time I can't access that page in Staging (reported on Slack), so will follow up later.

**Comment by CGillen** [comment]
Fixed during #2470 with PR #2649

**Comment by carakey** [comment]
Still having the exact same issue, including on the exact same item from my September 21 comment. Maybe it still isn't clear what problem I'm describing..? See the highlighted text in the green boxes in the screenshot below. Whatever field is closest to the halfway point where the metadata splits into two columns, the line of text gets bisected so the top half of a single line appears at the bottom of column 1, and the bottom half of the same line of text appears at the top of column 2. Sometimes it's initially fine but resizing the window or zooming out causes the problem; sometimes the problem is solved by resizing the window or zooming in. 

It's as though Safari is dividing the metadata text exactly in half across the two columns, so an even number of total lines of text in the metadata is OK, but an odd number of total lines means the middle one gets split into 0.5 + 0.5. 

(Is it possible I'm literally the only person this is happening to??)

![Screen Shot 2023-01-03 at 12 08 06](https://user-images.githubusercontent.com/17655103/210433438-8da19bd7-8bf9-43cc-931a-2a9225172808.png)

**Comment by straleyb** [comment]
The collision issue is solved by updating safari. It cascades like expected following the div cut offs.

The issue where its slicing the metadata word in half is a deeper issue with how hyrax is rendering the metadata in a 2 column psudo-table and how safari handles 2 column layouts. We can reproduce the issue onto other websites by copying in our css.

**Comment by carakey** [comment]
I updated to the latest version of Safari and still experience the issue. I cannot QA-pass this ticket because it's still occurring for me. If it needs to be closed without resolution or recategorized as not MVP and filed away for later, then so be it. 

Ceding this decision to someone else @shieldsb @CGillen

**Comment by CGillen** [comment]
@jsimic I thought I commented this earlier but i'm not seeing it anymore, sorry if you got another ping from somewhere else 🤷‍♂️ 

Currently metadata is displayed top-to-bottom-left-to-right, eg:
1 4
2 5
3 6
Would left-to-right-top-to-bottom be acceptable/better? eg:
1 2
3 4
5 6
This is based on the metadeities work show page metadata ordering: https://docs.google.com/spreadsheets/d/14xLkWt8KI9jCdlvPrNATgORngJEhXKOCoV0LAew1BQ4/edit#gid=1891520168

This turns out to be the correct way to use this CSS and fixes the issue

**Comment by petersec** [comment]
@jsimic @CGillen @teamestreet Would it be possible for someone to mock up what this might look like? I'm having a hard time visualizing. Perhaps we could do that and bring it to POSM for discussion?

**Comment by CGillen** [comment]
@petersec 
Current:
<img width="1594" alt="image" src="https://github.com/OregonDigital/OD2/assets/11052958/beb71ec9-bdcd-4e3f-abda-e2218540fdb3">

L-R-T-B:
<img width="1594" alt="image" src="https://github.com/OregonDigital/OD2/assets/11052958/cd1c62cc-b75d-40f9-9bd7-ab847ec863b6">

**Comment by petersec** [comment]
Thanks, @CGillen. If this fixes the problem, it seems totally fine to me

**Comment by CGillen** [comment]
@jsimic @teamestreet Any other thoughts?

**Comment by jsimic** [comment]
Looks good!

**Comment by shieldsb** [comment]
Spacing looks good, no overlap. But, I did see several that split the identifier field between columns. 
![OD column spacing](https://github.com/OregonDigital/OD2/assets/53542788/8e301d9c-81e8-4577-bd19-234bf9ef5c7a)
